# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -U postgres -c 'CREATE DATABASE klimageo;'
  - psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'password';"
  - psql -U postgres klimageo -f ${TRAVIS_BUILD_DIR}/travis/create_tables.sql
  - cp ${TRAVIS_BUILD_DIR}/travis/pgpass ~/.pgpass
  - chmod 0600 ~/.pgpass
after_success:
  - psql -U postgres -c 'DROP DATABASE klimageo;'
  - psql -U postgres -c 'CREATE DATABASE klimageo;'
  - psql -U postgres klimageo -f ${TRAVIS_BUILD_DIR}/travis/create_tables.sql
  - Rscript -e 'covr::codecov()'
