# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
addons:
  postgresql: "9.4"
  apt:
    packages:
      - unixodbc-dev
      - odbc-postgresql
services:
  - postgresql
before_script:
  - psql -U postgres -c 'CREATE DATABASE klimageo;'
  - psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'password';"
  - psql -U postgres -f ${TRAVIS_BUILD_DIR}/travis/create_tables.sql
  - odbcinst -i -s -h -f ${TRAVIS_BUILD_DIR}/travis/odbc.ini
#after_success:
#  - psql -U postgres -c 'DROP SCHEMA public CASCADE;'
#  - psql -U postgres -c 'CREATE SCHEMA public;'
#  - psql -U postgres -f ${TRAVIS_BUILD_DIR}/travis/create_tables.sql
#  - Rscript -e 'covr::codecov()'
